Category.destroy_all

puts "Create Category"
parent1 = Category.create :code => 'P001' , :name => 'Dining Room', :description => 'Dining Room Furniture'
parent2 = Category.create :code => 'P002' , :name => 'Bed Room' , :description => 'Bed Room Furniture'
parent3 = Category.create :code => 'P003' , :name => 'Living Room' , :description => 'Living Room Furniture'
parent4 = Category.create :code => 'P004' , :name => 'Kitchen Room' , :description => 'Kitchen Room Furniture'
cat1 = Category.create :code => 'C001' , :name => 'Buffets' , :category_id => parent1.id , :description => "Buffets and sideboards are becoming a must have for every home, think vital storage, timeless style and also a place to display all your favourite home-wares. They work in your dining room, lounge room and bedroom. With timber, lacquered, low line, and spacious options in a range of sizes, you should find your perfect design that's scandi, modern, conetmporary or luxe inspired."
cat2 = Category.create :code => 'C002' , :name => 'Dinner Chairs' , :category_id => parent1.id , :description => "Our dining chair collection includes pieces that will work for any dining room look, everything from clean and cool Scandi to modern mid-century inspired designs. The most important thing is to find that balance between comfort and style with the aim being to find the perfect seating to keep your friends and family at the table! We have sourced and selected well designed, high-quality chairs in a range of materials with solid timber, metal, upholstered, fabric, leather and padded options available."
cat3 = Category.create :code => 'C003' , :name => 'Dinner Tables' , :category_id => parent1.id , :description => "A dining table is always a focal point, our advice; buy once and buy well. Whatever look you are channeling in your dining room, we have a range of tables with timber, metal and glass top designs that are square, round, oval and rectangle. Short on space or lot's of people to feed, we have 90cm - 240 cm tables. Just love to entertain? Maybe an extension dining table will work for you. Think Hamptons, Scandi, industrial or modern inspired and everything in between"
cat4 = Category.create :code => 'C004' , :name => 'Extension Dining Tables' , :category_id => parent1.id , :description => "When it comes to interior design, it’s not all about style. Here at Life we value brains as well as beauty, and there are few smarter purchases than investing in an extension dining table. After all, the dining room is as much a heart of the home as the kitchen, so give yourself the versatility, and make your space work for you."
cat5 = Category.create :code => 'C005' , :name => 'Dining Sets' , :category_id => parent1.id , :description => "Take the stress out of matching your table and chairs, with our great value dining packages. We have done the hard work for you and pulled together perfect combinations of timber, metal, upholstered and painted dining sets that will work whatever your style. With scandi, modern, contemporary, and industrial designs to seat two, four, six, eight or ten people and in round, square and rectangle shapes we should have a solution that works for you. Whether you have a compact room or heaps of space and plenty of people to cater for."
cat6 = Category.create :code => 'C006' , :name => 'Bed Frams' , :category_id => parent2.id , :description => "The bed is usually the centre piece so allow it to take centre stage, we have timber, metal and upholstered options, whether you want to make a statement or keep things calm and neutral we more than likely have what you are looking for. With designer beds and on trend looks, think modern, contemporary, scandi and luxe in king, queen, double and single sizes. Pair with the perfect bedside tables, and clever storage and you have a complete room that is functional, stylish and relaxing."
cat7 = Category.create :code => 'C007' , :name => 'Bed Heads' , :category_id => parent2.id , :description => "A bed head is an easy, minimal effort way to add some impact to your bedroom becoming a feature and focal point, only making your bed that bit cosier. We have king, queen, double and single options in upholstered, timber, metal and leather styles. Layer up your bedding and add plenty of cushions for a great nights sleep. Match with your perfect bedside tables, and hang a favourite print above your bed for on trend style and a bedroom you never want to leave."
cat8 = Category.create  :code => 'C008' , :name => 'Armchairs' , :category_id => parent3.id , :description => "An armchair or two are great additions to any lounge space, as replacement for an extra sofa, or to complete a full suite if you have the space. They are cosy, welcoming and always on trend, with fabric and leather options, combined with timber or metal frames and legs in a range of shapes and sizes. Mid century inspired, scandi, luxe and contemporary designs that would sit just as well in a bedroom corner, a reading nook or even a country kitchen come dining space,"
cat8 = Category.create  :code => 'C009' , :name => 'Shelving Units' , :category_id => parent3.id , :description => "Shelving units are timeless and throwing a good book away is never easy, so create your own library and display you favourite reads for everyone to see. Mix in some favourite photos, a vase you love or a mantle clock and make it a collection of all your best bits and pieces. Even add a bottle of something and your best glasses, to have on hand whenever you need. Think outside the box when it comes to open storage solutions like shelving and it easily becomes a design element that can create some interest and show a bit of personality. We have sourced solid timber and metal options, that are narrow or wide and in scandi, modern and contemporary designs, so will more than likely have exactly what you're looking for."
cat9 = Category.create  :code => 'C010' , :name => 'Bar Stools' , :category_id => parent4.id , :description => "Our bar stool collection is one that we are proud of, we have created a range that we hope covers all bases and offers you choice, quality, and style. We have industrial, modern, contemporary, Scandi, luxe and Hampton inspired looks that will suit every kitchen. It is an easy and affordable way to update your kitchen space with timber, metal, and plastic bar stool options in both 65cm counter height and 75cm bar height. Don't be afraid to add a pop of colour, or a dash of glamour, choose a style you love and that works for your home."
cat10 = Category.create  :code => 'C011' , :name => 'Low Stools' , :category_id => parent4.id , :description => "Low stools are the ultimate multi-functional furniture item, they work as extra seating, a side table or foot rest... the possibilities are endless and it never hurts to have a couple handy for when you have a full house. They can be stackable, colourful or cool, we have timber, metal, plastic in modern, contemporary, scandi or industrial looks. For that casual kitchen table, a kids room or commercial space we have a range that are affordable and just won't let you down."

Product.destroy_all

puts "Create Product"
p1 = Product.create :code => 'P001' , :name => "Anja Woven Open Buffet (Teak)" , :dimension => "	168W x 47.5D x 95H cm" , :brand => "GlobeWest" , :style => "Modern" , :category_id => cat1.id , :image => "https://www.lifeinteriors.com.au/media/catalog/product/cache/1/thumbnail/1200x/17f82f742ffe127f42dca9de82fb58b1/b/u/xbu-glw-anja-tea-1.jpg.pagespeed.ic.I0gnbzMGiw.jpg" , :description => "This sophisticated buffet sideboard features three natural rattan doors and solid Teak construction and blends effortlessly with different styles."
p2 = Product.create :code => 'P002' , :name => "Jaden Dining Chair (Oak)" , :dimension => "52W x 48.5D x 45SH x 82H cm" , :brand => "Life Interiors" , :style => "Contemporary" , :category_id => cat2.id , :image => "https://www.lifeinteriors.com.au/media/catalog/product/cache/1/thumbnail/1200x/17f82f742ffe127f42dca9de82fb58b1/d/c/xdc-bia-jade-oak-pu-grey-2_2.jpg.pagespeed.ic.lMufyBND_S.jpg" , :description => "This is a low maintenance, hard wearing and practical dining solution that does not compromise on style and comfort, featuring single moulded Polypropylene frame and padded leatherette cushion. A Danish inspired design, the single moulded seat is comfortable and perfect for long sittings."
p3 = Product.create :code => 'P003' , :name => "Circa Square Dining Table (70cm)" , :dimension => "70W x 70D x 77H cm" , :brand => "Karpenter" , :style => "Contemporary" , :category_id => cat3.id , :image => "https://www.lifeinteriors.com.au/media/catalog/product/cache/1/thumbnail/1200x/17f82f742ffe127f42dca9de82fb58b1/d/t/dt-kar-circ-squ-70cm-oak-1_1.jpg" , :description => "The Circa range combines timelessly modern design with exquisite craftsmanship, and luxurious solid wood with sumptuous natural finishes. Using sustainably harvested timber, the Circa Square Dining Table 70cm will suit any contemporary dining room for decades to come."

User.destroy_all
puts "Create user"
u1 = User.create :first_name => 'admin', :last_name => 'system', :email => 'admin@ga.co', :admin => true, :password => 'chicken'
u2 = User.create :first_name => 'Mee', :last_name => 'K', :email => 'mee@ga.co', :admin => false, :password => 'chicken'

# Inventory.destroy_all

# puts "Create Inventory"
# Inventory.create :code => "INV0001", :product_id => p1.id, :inventory_date => '2019-04-12', :price => 59.40, :quantity => 24, :user_id => u1.id
# Inventory.create :code => "INV0002", :product_id => p2.id, :inventory_date => '2019-05-01', :price => 65, :quantity => 10, :user_id => u1.id